name: moobazir_user
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.6.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  retrofit: ^4.2.0
  json_annotation: ^4.9.0
  go_router: ^14.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  freezed_annotation: ^2.4.1
  font_awesome_flutter: ^10.6.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  retrofit_generator: 9.7.0
  json_serializable: ^6.9.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/product/
    - assets/images/merchant/
